# markdown: redcarpet
baseurl: /planet-of-the-universe
exclude: ['README.md']
permalink: pretty


collections:
  comets:
    output: true
    permalink: /comets/:path

  # posts:
  #   output: true
  #   permalink: /posts/:path/